imu_topic: "/sensors/imu"
imu_rate: 400
measure_rate: 100 # Rate to which imu data is subsampled
sequence_duration: 10800 # duration of the sequence (in seconds)
sequence_offset: 0 # sequence start within the recorded data (in seconds)